#!/usr/bin/env node
/**
 * Regenerates src/tool-snapshot.ts from the live endpoint.
 *
 * The stdio proxy serves that snapshot from tools/list when it runs without
 * SEO_API_KEY, which is how registries such as Glama introspect a server. Run
 * this after the hosted tool list changes:
 *
 *   npm run build && SEO_API_KEY=vseo_... npm run snapshot
 */
import { writeFileSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const apiKey = process.env.SEO_API_KEY?.trim();
if (!apiKey) {
  process.stderr.write("snapshot-tools: SEO_API_KEY is not set\n");
  process.exit(1);
}
const url = new URL(process.env.SEO_API_URL?.trim() || "https://app.getcited.dev/api/mcp");

const client = new Client({ name: "getcited-snapshot", version: "0.0.0" });
await client.connect(
  new StreamableHTTPClientTransport(url, {
    requestInit: { headers: { Authorization: `Bearer ${apiKey}` } },
  }),
);

const tools = [];
let cursor;
do {
  const page = await client.listTools(cursor === undefined ? {} : { cursor });
  tools.push(...page.tools);
  cursor = page.nextCursor;
} while (cursor !== undefined);
await client.close();

const out = new URL("../src/tool-snapshot.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/snapshot-tools.mjs from ${url.href}. Do not edit by hand.\n` +
    `// Served from tools/list only when the proxy runs without SEO_API_KEY.\n` +
    `import type { Tool } from "@modelcontextprotocol/sdk/types.js";\n\n` +
    `export const TOOL_SNAPSHOT: Tool[] = ${JSON.stringify(tools, null, 2)};\n`,
);
process.stdout.write(`wrote ${tools.length} tools to src/tool-snapshot.ts\n`);
