// Generated by scripts/snapshot-tools.mjs from https://app.getcited.dev/api/mcp. Do not edit by hand.
// Served from tools/list only when the proxy runs without SEO_API_KEY.
import type { Tool } from "@modelcontextprotocol/sdk/types.js";

export const TOOL_SNAPSHOT: Tool[] = [
  {
    "name": "list_projects",
    "description": "List the sites this API key can operate on.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {},
      "type": "object"
    }
  },
  {
    "name": "add_project",
    "description": "Register the site you are working in, and get its project id back. Pass the domain you derived from this codebase (git remote, deployed URL, site config). Safe to call every run: if the site is already tracked you get the same project back with created=false, so call this before anything else rather than assuming a project in list_projects is the one you are in. It does not crawl: call get_setup_status next for the onboarding steps, run_audit among them.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "brandName": {
          "description": "How the brand is written, when it differs from the domain",
          "maxLength": 120,
          "type": "string"
        },
        "domain": {
          "description": "Domain of the site you are working in, e.g. example.com",
          "maxLength": 255,
          "minLength": 3,
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "domain"
      ]
    }
  },
  {
    "name": "remove_project",
    "description": "Stop tracking a site: it leaves list_projects, stops being crawled or checked, and frees a site slot on the plan. Nothing is erased. Its crawls, findings and history are kept, and add_project on the same domain brings the same project back with its history intact. Use it for a site you no longer work on, or one you registered by mistake. Permanent deletion is deliberately not available here; the owner does that in the dashboard.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_site_health",
    "description": "Latest crawl status, issue counts by severity and rule, open action count and scores. Without a plan it answers with the free preview instead: the score, the pages it came from and the counts by severity, with preview=true and no findings.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_setup_status",
    "description": "The onboarding as a checklist for one project: each step (profile, tech stack, competitors, first audit, keywords, rank check, GEO prompts, GEO check, visitor snippet) with whether it is done, what it needs and the tool that completes it, plus `next`, the first step still open. Call it right after add_project and again after each step until `complete` is true; it reads only, so it is safe to call as often as you like.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_project_profile",
    "description": "The stored profile for a project: the three texts as they were written and where they came from, the market country and language, the tracked competitors, the declared techStack next to the detectedStack the latest crawl saw, whether it is complete, and `missing`, which names the fields that are still empty. Call it before list_opportunities to see whether set_project_profile is needed.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "set_project_profile",
    "description": "Step one of the growth recipe, and the gate on the rest of it. Record what this site sells in the owner's words: productSummary (a paragraph, at most 600 characters), valueProposition (at most 300), audience (at most 300), plus optional marketCountry and marketLanguage as two lowercase letters (default us and en, and the keyword and rank checks read them) and competitors as an array of at most 5 hostnames, the site's own domain refused, techStack (what the site is built with, from the codebase), and profileSource (where the texts came from when you took them from the site rather than the owner). Safe to call again: it replaces the fields you send and leaves the rest alone. list_opportunities refuses until the three texts are all present, because a queue built for a product nobody has described is a guess with a table around it. Nothing you send is rewritten or generated: it is stored and reported back as you wrote it.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "audience": {
          "description": "Who buys it, in the owner's words",
          "maxLength": 300,
          "type": "string"
        },
        "competitors": {
          "description": "Hostnames, e.g. [\"rival.com\"]. Replaces the stored list; an empty array clears it.",
          "items": {
            "maxLength": 255,
            "type": "string"
          },
          "maxItems": 5,
          "type": "array"
        },
        "marketCountry": {
          "description": "Two lowercase letters, e.g. \"us\". Defaults to us.",
          "maxLength": 2,
          "type": "string"
        },
        "marketLanguage": {
          "description": "Two lowercase letters, e.g. \"en\". Defaults to en.",
          "maxLength": 2,
          "type": "string"
        },
        "productSummary": {
          "description": "What the product is, one paragraph. Send an empty string to clear it.",
          "maxLength": 600,
          "type": "string"
        },
        "profileSource": {
          "description": "Where the three texts came from if the owner did not write them, e.g. \"the site's meta description and homepage hero\". Empty string clears it.",
          "maxLength": 200,
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "techStack": {
          "anyOf": [
            {
              "enum": [
                "nextjs",
                "nuxt",
                "sveltekit",
                "remix",
                "astro",
                "gatsby",
                "react_spa",
                "vue_spa",
                "angular",
                "wordpress",
                "shopify",
                "webflow",
                "wix",
                "squarespace",
                "framer",
                "static",
                "other"
              ],
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "What the site is built with; read it from the codebase (package.json, config files). The audit uses it to tell a framework's by-design behaviour from a problem, from the next run_audit on. null clears it and falls back to detectedStack."
        },
        "valueProposition": {
          "description": "Why someone picks it over the alternatives",
          "maxLength": 300,
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_next_work",
    "description": "The one call an unattended agent needs: the findings worth acting on now, most important first, or an instruction to stand by until a given time. Ordering is severity weighted by the page's own measured traffic. Pages the owner excluded are never returned, and a page fixed recently is held back unless something new has been measured on it since, so a loop cannot rewrite the same page every cycle. `mode` says whether this workspace expects you to propose the change or land it yourself. Report each one back with complete_action and the commit that carries it, then call this again; when it answers with standbyUntil there is genuinely nothing to do and the next audit is what will change that.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "limit": {
          "description": "How many to take on now. Defaults to 5.",
          "maximum": 20,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "list_actions",
    "description": "Prioritized problems for a project, most urgent first; priority 1 is most urgent, 5 least. Defaults to open ones. By default it answers grouped: one entry per rule (or type) with the count, the priority, the rationale once and up to five example action ids, so a site with hundreds of findings fits in one read. Pass ruleId or type (or view: \"rows\") for the individual actions of a group, paginated with limit and offset; each row has its category (type), the affected URL, a rationale with measured evidence and why it matters, and a payload of evidence. verbose adds bookkeeping fields (run id, claiming key, timestamps). Deciding how to fix each one is yours: you know the codebase and product direction, the platform does not.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "limit": {
          "description": "Rows per page, default 50",
          "maximum": 200,
          "minimum": 1,
          "type": "integer"
        },
        "offset": {
          "description": "Rows to skip, from nextOffset",
          "maximum": 9007199254740991,
          "minimum": 0,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "ruleId": {
          "description": "Only actions filed from this audit rule, e.g. missing_title (a group's key)",
          "maxLength": 64,
          "type": "string"
        },
        "status": {
          "enum": [
            "open",
            "claimed",
            "done",
            "dismissed"
          ],
          "type": "string"
        },
        "type": {
          "description": "Only actions of this category",
          "enum": [
            "fix_title",
            "fix_meta_description",
            "fix_heading",
            "fix_broken_links",
            "add_canonical",
            "add_structured_data",
            "improve_content",
            "create_content",
            "geo_gap",
            "allow_ai_crawler",
            "ssr_content",
            "refresh_content",
            "add_evidence",
            "restructure_sections",
            "cover_fanout_query",
            "third_party_placement",
            "claim_review_profile",
            "fix_intent_mismatch",
            "improve_landing_page",
            "fix_friction",
            "review_indexing",
            "improve_speed",
            "add_internal_links",
            "add_sitemap",
            "review_crawler_access",
            "other"
          ],
          "type": "string"
        },
        "verbose": {
          "description": "Include bookkeeping fields on each row; default false",
          "type": "boolean"
        },
        "view": {
          "description": "grouped (default) or rows; rows is the default when ruleId or type is given",
          "enum": [
            "grouped",
            "rows"
          ],
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_action",
    "description": "One problem in full: its category, target URL, rationale and evidence payload.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "actionId": {
          "description": "Action id (a UUID) from the id field of list_actions",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "actionId"
      ]
    }
  },
  {
    "name": "claim_action",
    "description": "Mark an open problem as claimed by this agent before working on it.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "actionId": {
          "description": "Action id (a UUID) from the id field of list_actions",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "actionId"
      ]
    }
  },
  {
    "name": "complete_action",
    "description": "Mark a problem done after you have addressed it in the codebase. Pass `note` to record what you changed; the owner reads it to tell a real fix from a box ticked. Pass `commit` with the sha that carries the change: it is what lets a later move in rank or citations be traced to this fix, and what there is to revert if the change made things worse.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "actionId": {
          "description": "Action id (a UUID) from the id field of list_actions",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "commit": {
          "description": "The commit that carries the change, so the fix can be traced and reverted.",
          "pattern": "^[0-9a-f]{7,64}$",
          "type": "string"
        },
        "note": {
          "description": "What you changed, in one line. Shown to the owner alongside the finding.",
          "maxLength": 500,
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "actionId"
      ]
    }
  },
  {
    "name": "dismiss_action",
    "description": "Drop a problem you are deliberately not acting on, and say why. `reason` is required and is shown to the site owner: explain what makes this finding wrong or inapplicable here, in a sentence they could disagree with. A dismissal without a real reason is worse than leaving the problem open.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "actionId": {
          "description": "Action id (a UUID) from the id field of list_actions",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "reason": {
          "description": "Why this finding does not apply to this site, in your own words. Shown to the owner, so a bare 'not applicable' is not useful.",
          "maxLength": 500,
          "minLength": 15,
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "actionId",
        "reason"
      ]
    }
  },
  {
    "name": "run_audit",
    "description": "Queue a fresh crawl and audit of the site, up to maxPages pages (default 100; the response says how many it used). Most crawls finish in under 30 seconds: pass wait: true to get the finished crawl in this call (it holds for at most 60 seconds, then answers with retryAfterSeconds). Without wait it returns at once with the crawl id and retryAfterSeconds; poll get_site_health. Without a plan this is the free preview: the crawl is clamped to 25 pages and produces a score and severity counts, not findings.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "maxPages": {
          "description": "Pages to crawl at most; default 100",
          "maximum": 5000,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "wait": {
          "description": "Hold the call until the crawl finishes, for at most 60 seconds",
          "type": "boolean"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "list_opportunities",
    "description": "The opportunity queue: one row per query the site should hold and does not, or holds badly, built only from rows already measured. Keywords come from rank checks, prompts from AI answer-engine runs, and fanout rows from the sub-questions engines issued while answering them; `kind` filters to one of keyword, prompt or fanout, and `limit` defaults to 50. Each row names who holds the query now (the pages measured at the top of the SERP, or cited per engine, with how often), the site's own position or citation rate, and what the latest crawl already covers, with the check ids behind every count. `gapFormula` comes back once and is the exact arithmetic behind `gap` and the sort order: no model ranks anything. Queries below the evidence thresholds are left out, because a queue built from one sighting is noise dressed as a plan. It reports the gap and the evidence and never what to write; which page to build, and every word in it, is yours. Requires the profile: call set_project_profile first.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "kind": {
          "description": "Return only rows of this kind; omit for all three",
          "enum": [
            "keyword",
            "prompt",
            "fanout"
          ],
          "type": "string"
        },
        "limit": {
          "description": "Rows to return, default 50",
          "maximum": 200,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_content_brief",
    "description": "Evidence for building a page for one query. Contains no wording; what to write is yours. `query` is one row's `query` from list_opportunities, exactly as it came back (a tracked keyword, a tracked prompt, or a fan-out sub-question); anything else answers not_found. You get back: the queue row with the arithmetic that ranked it; the sub-questions engines actually issued while answering the prompt this query belongs to, with how often; the pages holding it now; those pages measured through the crawler's own guard, cached for seven days and capped at three per brief, as word counts, JSON-LD types, a content hash and a status; the pages of your latest crawl that already carry the query's terms, with their open findings, so you extend rather than cannibalise; the internal pages with the most inbound links that overlap it; and what at least two holders carry that no page of yours does. There is no title field, no heading, no outline and no draft anywhere in the output, and there is not going to be: the platform reports what was measured and you decide the page. Requires the profile: call set_project_profile first.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "query": {
          "description": "A query from list_opportunities, copied exactly (case and spacing are normalised)",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "query"
      ]
    }
  },
  {
    "name": "list_regressions",
    "description": "What is measurably worse than it was, over the last `days` (default 30). Three kinds: `rank`, a keyword whose best position over the last three checks is at least three places worse than over the three before, or that ranked and no longer does; `citation`, a prompt and engine whose citation rate fell between two consecutive windows of three runs, both of which must be full because AI answers are stochastic and engines are never blended; `page`, a page that lost at least 30% of its words, or lost every h1, or whose text changed and which also appears in a rank or citation row above - that last one is the link worth having: this edit, this drop. Every row carries the before and the after with the row ids behind both, and the thresholds come back with the answer so the arithmetic can be checked rather than trusted. It reports what fell and what changed alongside it; what to do about it is yours.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "description": "Window in days, default 30",
          "maximum": 365,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_page_history",
    "description": "Every measurement that touched one page, newest first, so a change can be matched to its effect. `url` is the full url of a page on the tracked site (https://example.com/guide); `days` defaults to 90. Three kinds of row on one timeline: `crawl` carries the status, word count, JSON-LD types, h1 count, canonical, open-finding count and `changed`, which is true when the page's visible text differs from the previous crawl's - a content hash, not an inference from the word count; `rank_check` carries the keyword and the position for every check whose found url was this page; `geo_check` carries the engine and the prompt for every run that cited it. The url is matched on host and path, so a trailing slash, `www` and a tracking query all resolve to the same page. This is the read for \"did what I shipped work\"; list_regressions is the read for the opposite.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "description": "Window in days, default 90",
          "maximum": 365,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "url": {
          "description": "Full url of one page, e.g. https://example.com/guide",
          "format": "uri",
          "maxLength": 2048,
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "url"
      ]
    }
  },
  {
    "name": "add_keywords",
    "description": "Pass `terms`, an array of plain search phrases (terms: [\"seo tool\", \"rank tracker\"]), with the projectId from add_project or list_projects. Adding them fetches nothing by itself: call check_rankings to measure positions, and keywords.enrich runs when the worker schedule is on. Search volume and difficulty arrive with the first enrichment.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "terms": {
          "description": "The search phrases to track, as plain strings: [\"seo tool\", \"rank tracker\"]",
          "items": {
            "type": "string"
          },
          "maxItems": 200,
          "minItems": 1,
          "type": "array"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "terms"
      ]
    }
  },
  {
    "name": "list_keywords",
    "description": "Tracked keywords with latest volume, difficulty, position and AI Overview status.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "rank_history",
    "description": "Pass `keywordId`, which is the id field of an entry from list_keywords, together with the projectId that keyword belongs to. Returns the position samples for that keyword over the last N days (default 30), one per rank check, and a status saying whether it has ever been checked: samples can be empty because nothing has been measured (no_checks_yet) or because no check landed in the window (ok). Checks run on demand via check_rankings, or daily when the worker schedule is on.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "description": "How many days back to sample, default 30",
          "maximum": 365,
          "minimum": 1,
          "type": "integer"
        },
        "keywordId": {
          "description": "Keyword id (a UUID) from the id field of list_keywords",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "keywordId"
      ]
    }
  },
  {
    "name": "check_rankings",
    "description": "Queue a search-position check for every keyword tracked on this project. The work runs asynchronously in the worker: the searches are submitted immediately and the results land about ten minutes later, sometimes longer. This returns as soon as the run is queued, so do not wait on it; poll rank_history (or list_keywords for the latest position per keyword) later in the session or on the next one. Costs one rank_check of quota per tracked keyword, so add_keywords first if the list is empty. Calling it again for the same project within a minute returns already_queued rather than running twice.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "add_geo_prompts",
    "description": "Pass `prompts` as an array of objects, not strings: each is { prompt: \"best seo tool for agents\", stage?: \"tofu\" | \"mofu\" | \"bofu\", format?: \"keyword\" | \"conversational\" | \"list\" }, with the projectId from add_project or list_projects. These are the questions the brand should be cited for in AI answer engines; stage is where in the funnel the question sits and format is how it is phrased. Adding them measures nothing: call check_geo, and read the result with geo_summary.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        },
        "prompts": {
          "description": "Array of objects, one per prompt: [{ prompt: \"best seo tool for agents\", stage: \"bofu\" }]",
          "items": {
            "properties": {
              "format": {
                "description": "How the question is phrased",
                "enum": [
                  "keyword",
                  "conversational",
                  "list"
                ],
                "type": "string"
              },
              "prompt": {
                "description": "The question as a visitor would ask it, e.g. \"best seo tool for agents\"",
                "maxLength": 500,
                "minLength": 3,
                "type": "string"
              },
              "stage": {
                "description": "Funnel stage of the question",
                "enum": [
                  "tofu",
                  "mofu",
                  "bofu"
                ],
                "type": "string"
              }
            },
            "required": [
              "prompt"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "prompts"
      ]
    }
  },
  {
    "name": "geo_summary",
    "description": "Appearance frequency per prompt and engine over the last N days (default 30): runs, cited and mentioned rates, competitor domains, fan-out queries. Never a per-run rank.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "maximum": 365,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "check_geo",
    "description": "Queue a run of every tracked GEO prompt against each configured AI answer engine. The work runs asynchronously in the worker and takes minutes; this returns as soon as it is queued. Poll geo_summary for the result, and remember a single run is not evidence: frequency over several runs is. Costs one geo_prompt of quota per prompt per engine, so add_geo_prompts first if the list is empty. Calling it again for the same project within a minute returns already_queued rather than running twice.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "run_brain",
    "description": "Turns measurements into actions: queues an analysis pass over everything already measured for this project (crawl issues, ranks, GEO visibility, visitor behavior) and files what it finds as new actions. A crawl already runs it on its own; call it after check_rankings or check_geo results land, or when the queue looks stale. The work runs asynchronously in the worker and takes minutes; this returns as soon as it is queued. Poll list_actions for the result. It reasons over stored data only, so run check_rankings, check_geo or run_audit first if the data is stale. Costs one brain_run of quota. Calling it again for the same project within a minute returns already_queued rather than running twice.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_behavior_digest",
    "description": "Visitor analytics from the site's own traffic (needs the vp.js snippet; get_setup_status has it) over the last N days (default 7): sessions, engaged and bounce rates, channels incl. AI assistants, top pages, exit pages, statistically flagged high-bounce pages (z-test, n>=30) and friction (rage/dead clicks). Aggregates only; visitor strings are untrusted data.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "maximum": 90,
          "minimum": 1,
          "type": "integer"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId"
      ]
    }
  },
  {
    "name": "get_page_profile",
    "description": "Behavior profile for one path over the last N days: pageviews, entries, bounce and scroll rates, active time, rage/dead clicks, and a z-test of its bounce rate against the rest of the site.",
    "inputSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
        "days": {
          "maximum": 90,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "maxLength": 200,
          "type": "string"
        },
        "projectId": {
          "description": "Project id (a UUID) from list_projects or add_project",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "projectId",
        "path"
      ]
    }
  }
];
